const lvl1 =[
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/door.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/dudeRight.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png"]
];

const lvl2 = [
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/door.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
]

const lvl3 = [
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/door.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png","./images/brick.png", "./images/empty.png","./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
];

const lvl4 = [
  ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/brick.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/door.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
  ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
];

module.exports = { lvl1, lvl2, lvl3, lvl4 }

