const lvl1 = {
  password: 'tcP',
  board: [
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/door.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/dudeRight.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png"]
  ]
};

const lvl2 = {
  password: 'Aro',
  board: [
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/door.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
  ]
};

const lvl3 = {
  password: 'arohanlovescoffee',
  board: [
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/door.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png","./images/brick.png", "./images/empty.png","./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
  ]
};

const lvl4 = {
  password: 'jeffisawesome',
  board: [
    ["./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/block.png", "./images/block.png", "./images/brick.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/dudeLeft.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/block.png", "./images/block.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/door.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"],
    ["./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/brick.png", "./images/brick.png", "./images/brick.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png", "./images/empty.png"]
  ]
};

module.exports = { lvl1, lvl2, lvl3, lvl4 }

